nelmio_api_doc:
    documentation:
        info:
            title: Books Guide
            description: This api made with symfony!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1 # Accepts routes under /api except /api/doc
